### ISSUE TITLE
support s6 readiness notification

### ISSUE THREAD

**Issue by eburghar** [just-containers/socklog#2]
As socklog is already forked to use skanet lib, an interesting feature would be adding s6 startup notification (`-d fd`) so we can wait for socklog before starting dependent services. For now `run` has to be patched to something like

```bash
#!/usr/bin/execlineb -P

fdmove -c 2 1
s6-notifyoncheck -c "s6-test -S /dev/log"
s6-envuidgid -D 32768:32768 nobody
socklog unix /dev/log
```

and create a `/etc/services.d/socklog/notification-fd` file with the content `3` which is not optimal

**Comment by skarnet** [comment]
Just fyi: the next version of s6 will include a socklog equivalent, to avoid having to keep depending on socklog. The replacement will support readiness notification. 😉

**Comment by jprjr** [comment]
Ok - in that case I'll keep an eye out for the next s6 release and hold off on updating this socklog fork.

**Comment by eburghar** [comment]
@skarnet well, knowing that an alternative is coming with the same quality level than the rest of the suite, I can surely continue with `s6-notifyoncheck`. Many thanks for the amazing s6 software that gave me a fresh perspective on security and what really defines a supervision suite. Thanks also to @jprjr for the s6 overlay I use in all containers.

**Comment by hongkongkiwi** [comment]
What’s the planned release date?

**Comment by skarnet** [comment]
`s6-socklog` is already available in the master branch of s6, but this may not be very comfortable for integration because this branch is in significant flux at the moment (adding a lot of stuff before the next update).
The next release is planned for some time in September.

**Comment by skarnet** [comment]
The s6 release, containing `s6-socklog`, has been out for a while, and now s6-overlay v3.0.0.0 is out - providing a syslogd emulation that uses `s6-socklog` and making this socklog fork obsolete.
I'm closing this issue; please reopen if you have any concern.
